### PR TITLE
Unified the 3 graphics drivers.

### PR DESCRIPTION
**Pull request by db4ple**
Use with caution (tested with standard display, not yet ILI9486 or RA8875)
Changed launch config for OVI40 bootloader to run with GNU MCU Eclipse, breaks launch compatibility with GNU ARM Eclipse (the predecessor name).
Switched to internal builder also for DebugMCHF config much quicker turnaround in most cases

### CODE REVIEW

**Comment by db4ple** [comment]
Hi Slawek,
my first contribution.  BTW, enabling travis builds for your repository will automatically build the submitted code and show you the result. Strongly recommended when accepting contributions from strangers like me :-)
We have a "almost no warning policy" when accepting contributions, i.e. with too many strange warnings shown during build. reject contribution and ask for fixing the warnings before resubmitting. 
Do not accept pull requests which are not merging cleanly unless you created the reason for the conflict. Ask contributor to resolve conflicts before you merge pull request.

**Comment by sp9bsl** [comment]
Hi stranger :) 
I installed Travis. How to add file .travis.yml to make Travis run?

**Comment by db4ple** [comment]
Hi Slawek,
https://docs.travis-ci.com/user/getting-started/ 
Just do step 1 and 2. 
The .travis.yml file itself is already there and works (we use this in the main repo)

**Comment by sp9bsl** [comment]
Yes, i already did it. Merge now?

**Comment by sp9bsl** [comment]
When it starts to build?

**Comment by db4ple** [comment]
I will try to trigger the travis build by a fake "commit change".

**Comment by db4ple** [comment]
Now you can see it working...

**Comment by db4ple** [comment]
Click on details and wait a little to see the full show...

**Comment by sp9bsl** [comment]
what can i say WOOW!

**Comment by sp9bsl** [comment]
It runs on ubuntu i saw sudo somewhere...

**Comment by sp9bsl** [comment]
Where are the output files placed?

**Comment by db4ple** [comment]
Yes, it is Ubuntu 14.04 (you can scroll up to see the first lines of the start). 
Output files are placed in this mode nowhere. We use this for build testing only but travis can do a lot more stuff (we have not explored these possibilities, a kind contributor provided the basic .travis.yml and we sticked to it more or less).

**Comment by sp9bsl** [comment]
So now, after the virtual build have passed ok i can merge right?

**Comment by sp9bsl** [comment]
Ok, i did it. Now i have to fetch and rebase my local repo. Should i do `git rebase main/active-devel`?

**Comment by db4ple** [comment]
git fetch main
git rebase main/active-devel

You will notice some changes, earlier I commited some stuff and Andreas merged it. I don't know but it might create conflicts on your side but I hope not. In any case these are small issue anyway.

**Comment by db4ple** [comment]
BTW, if you don't like the outcome of a automated git rebase:
With `git reflog` you can see with a little effort which commit was before the rebase and you can reset your repo to this commit:

e.g. with
`git reset --hard HEAD@{3}`

**Comment by sp9bsl** [comment]
Something is wrong, i don't see the RA driver code.

**Comment by db4ple** [comment]
Locally you can't see the changes, since you merged in the GitHub repository. No automatic download from there.

**Comment by sp9bsl** [comment]
So, when i will be able to start changing files, and use changes you made?

**Comment by db4ple** [comment]
You have to bring your local repository up to the current state after you merged in GitHub.
1. `git fetch origin`
1. If before your GitHub merge your local branch was at same commit as GitHub : `git pull` or `git rebase origin/wip...` will do the same thing.

**Comment by sp9bsl** [comment]
Yes, there are conflicts:
image
[temp.zip](https://github.com/sp9bsl/UHSDR/files/1373519/temp.zip)

**Comment by db4ple** [comment]
Hi Slawek,
this was not so good.

**Comment by sp9bsl** [comment]
I didn't do any changes today, waiting to setup all.

**Comment by db4ple** [comment]
If you have unstaged changes, rebase will fail. 
Either discard your changes or stash them. 
If you don't know which changes there are, before doing anything do a `git status`
Now to get back to a safe state:
run `git reset --hard`

**Comment by db4ple** [comment]
And run `git status` and post the result

**Comment by sp9bsl** [comment]
image

**Comment by db4ple** [comment]
run `git log` please

**Comment by sp9bsl** [comment]
just the beginnig:
image

**Comment by db4ple** [comment]
Looks good.  We go back 2 commits:
`git reset --hard HEAD~2`
and we are in the original state

**Comment by db4ple** [comment]
Now do `git pull`

**Comment by sp9bsl** [comment]
image

**Comment by db4ple** [comment]
`git log` please (only the first page)

**Comment by sp9bsl** [comment]
I think at some point i was impatient :-)
image

**Comment by db4ple** [comment]
Ok. Now `git status`

**Comment by sp9bsl** [comment]
image

**Comment by db4ple** [comment]
Last but not least, we try to rebase again:
`git rebase main/active-devel` and hope it goes how I want it...

**Comment by sp9bsl** [comment]
image

**Comment by db4ple** [comment]
First open uhsdr_board.h
You will see the conflict (>>> ==== <<<)  It is a simple one.

**Comment by sp9bsl** [comment]
<<<<<<< HEAD
// should be fine now (Oct 2017), since SNAP now does not use any more memory
//#define USE_FREEDV_AND_SNAP // experimental!!!
=======
>>>>>>> Unified the 3 graphics drivers.

remove the text after >>>>>>   ?

**Comment by db4ple** [comment]
We take the choice between 
====
>>>>
Which is simply to delete the whole <<< === >>> range. Since the comment is now a few lines down.

So we fix this conflict. Now we have to use `git add uhsdr_board.h` (with correct path)

**Comment by sp9bsl** [comment]
ok, i added

**Comment by sp9bsl** [comment]
`git rebase --continue` ?

**Comment by db4ple** [comment]
And the conflict in the ui_lcd_hy28.c file is also simple:

<<<<<<< 76e78ab6e33c7cf9aa94cf6a981ae717d6ed1d52

    spi_reg_t tmpreg = SPI2->CR1;
    tmpreg &= ~(spi_reg_t)(SPI_BAUDRATEPRESCALER_256);
    tmpreg |= (spi_reg_t)(baudrate_prescaler);
=======
    uint16_t tmpreg = SPI2->CR1;
    tmpreg &= ~(uint16_t)((uint32_t) (SPI_BAUDRATEPRESCALER_256));
    tmpreg |= (uint16_t)((uint32_t) (baudrate_prescaler));

>>>>>>> Unified the 3 graphics drivers.


Here we take the upper choice. I'll explain why in a moment

**Comment by db4ple** [comment]
Before rebase --continue works you have to fix all merge conflicts and you have two.

**Comment by db4ple** [comment]
So please do the change to ui_lcd_hy28.c and do the git add.
After that `git rebase --continue`

**Comment by sp9bsl** [comment]
ok
image

**Comment by db4ple** [comment]
Oh dear, .settings/language.settings.xml again.

**Comment by sp9bsl** [comment]
yes i see it...

**Comment by sp9bsl** [comment]
Danilo, can we continue tomorrow?

**Comment by db4ple** [comment]
This file is a major pain. 
Close Eclipse. 
`git checkout mchf-eclipse/.settings/language.settings.xml`
and then git status should report no changes on this file anymore and we can proceed with rebase

**Comment by db4ple** [comment]
Happily, but I think with the checkout and rebase continue we are done.

**Comment by sp9bsl** [comment]
image

**Comment by db4ple** [comment]
`git rebase --continue` !!!
and we can go to sleep...

**Comment by sp9bsl** [comment]
image
amen :-)

**Comment by db4ple** [comment]
Good night...

**Comment by sp9bsl** [comment]
Good night too :-)

**Comment by sp9bsl** [comment]
Hi Danilo, 
why that strange type casting with prescaler?

**Comment by db4ple** [comment]
Because the STM32H7 HAL SPI peripheral has 32bit wide device registers, and for instance the prescaler constants now use the upper bits of the register. So much for compatibility between STM32F4/STM32F7/STM32H7. I noticed that STM has a different definition of "compatibility" between processor families than I have.
 
In the end we should use 32bit for all processors which then removes the need for the whole cast. But for unknown reasons I did not want to change anything outside that single function when I made the port to the H7. As you know, not everything one does makes 100% sense when looking at it later.

**Comment by db4ple** [comment]
BTW, can you do a "git push -f" so that your GitHub branch is updated. Thank you!

**Comment by sp9bsl** [comment]
ok i will, but not now. I'm in work now. About "compatibility": for me all HAL is a disaster, i don't like it...  I'm assembler man...

**Comment by db4ple** [comment]
Well please do anyway, it will only push your commits not your unfinished changes, but I want to verify that I can rebase correctly according to my own instructions. It is quite important for the other contributors (me for instance) to have the latest possible commit out there since it reduces the risk of large rework of ones own work.

**Comment by sp9bsl** [comment]
ok, this afternoon, sorry.

**Comment by sp9bsl** [comment]
I think also that it could be good i we prepare a place where the output files should be. Just for tests, for people that don't really want/are able to have all the development stuff.

**Comment by db4ple** [comment]
Hi Slawek, Andreas,

@df8oe: Maybe we use your repository approach and you put selected builds (with a different name) 

Or we figure out how to automatically use the travis build to produce some binaries and have them on github: https://docs.travis-ci.com/user/deployment/releases/

**Comment by df8oe** [comment]
Hi Danilo,

maybe later I can set up a web based automat which can build special binaries the user can select via dropdowns or radio buttons. At this stage I am unable to do this because nothing related to new branch is automated and eats to much time. But if we can use travis for this that would be great. I will have a look at the docs this evening.

**Comment by sp9bsl** [comment]
Travis would be good if it produces the same code like gcc locally (sorry if this it is stupid...).

**Comment by df8oe** [comment]
Travis is based on a Linux system and you can install the newest arm tools before you build (if you want)... You have the freedom to nearly do everything ;)

**Comment by db4ple** [comment]
Actually we are doing this: We download a newer compiler from the gcc arm site  and run it for the F7 build.

**Comment by db4ple** [comment]
BTW, we never had any issue with any of the compilers (except for differing binary size and error messages). In the end all errors could be related to human programming errors not compiler errors (as usual). There are compiler issues but we are not likely to experience them.

**Comment by db4ple** [comment]
If you build with Eclipse, you get slightly different binaries due to differing build process for Eclipse vs. make (which is used by travis) even with the same compiler. The reason is Windows. Under Windows with Eclipse we cannot build in the same way as under Linux to due to different command line length limitation (We hit the Windows limit if we link all files directly but not the Linux limit).  This has an impact on the optimization and link process -> different binaries. But I don't see this as an big issue. Never caused real trouble.

**Comment by sp9bsl** [comment]
Why i am asking: i had a two years ago big step: different (faster) build time and two times size low. I don't remember which version gcc was that but it was after i upgraded it. Anyway, it worked ok but that caused total test of everything... A week of testing and few people involved into.

**Comment by df8oe** [comment]
Build time and size of binaries can and will differ between different gcc Versions. That does not impact functionality - if binary is matching into flash of STM :)

**Comment by sp9bsl** [comment]
Andreas: speaking about flash size, after my Monday's commit we don't need to remove FreeDV. Do we have the limit of 512kB? You mention about survey.

**Comment by df8oe** [comment]
Limit is 512k-64k (32k are used by bootloader and 32k are "virtual EEPROM")

**Comment by sp9bsl** [comment]
ok.

**Comment by sp9bsl** [comment]
Danilo, i have this now:
image
Do `git push -f` ?
This is after our work last night.

**Comment by db4ple** [comment]
Yes.

**Pull request merged**
