### PR TITLE
Small fix (no functional change)

### PR DESCRIPTION
**Pull request by db4ple**
Just a very tiny correction (to test if my workflow works as expected and to make code a little more readable)

### CODE REVIEW

**Comment by sp9bsl** [comment]
Danilo,
i also have some changes, merge yours first then fetch and push mine?

**Comment by db4ple** [comment]
It is up to you. 
you can also push yours, see what my pull request does, merge and pull it from remote.

I.e. commit your local changes to the branch locally, then run 
`git push -f origin`
Now we will see how my pull request responds to that. If it merges cleanly on GitHub,
you finally do a  `git pull` and both branches (local/remote) should be the same again.

@df8oe is your better partner for this specific part (I never got a pull request to merge, I only create them in oher repos).

73
Danilo

**Comment by sp9bsl** [comment]
I pulled it, built and it works as before. So i think everything passed OK. I see your changes also.

**Comment by db4ple** [comment]
Hi Slawek,
thank you! I think, now we can be (more or less) confident that our way of working works as intended. Of course, in some cases a pull request may not go through after you pushing your changes after the pull request has been made. Then one (you) or the other (the pull request owner) has to do the nasty work of fixing that problem. 

I dusted off my mcHF F4 UI board, just waiting for the delivery of my "prototype" PCB which will allow me to build an adapter from the nasty 2x20pin 2mm pitch to a proper 2.54mm pitch and from this to the ILI9486 which I have here. Also have a RA8875 here. I will test both with SPI for the sake of reduced number of wires to connect...

Next interesting challenge is the way how we configure the builds for different graphics drivers. I added a rule which configures the "standard display" and from that 320x240 if no other information is given.
It is not acceptable that we have to change source code in order to switch the graphics driver build. 
With an external define no problem in Makefile.  With Eclipse this a little more trouble. Of course we can set a define in a build configuration but maintaining multiple build configurations which differ only in the defines is a nightmare since we have no such thing as build configuration B is A plus a define. These are all full copies. So whenever there is a file added, you would need to add this in N places (N being the number of fw configurations).

**Comment by sp9bsl** [comment]
Hi Danilo,
Problem of conflicts will rise when we try to change the same part of code, but then i think we can do it manually in small steps.
There is still problem where to place output files that are ready to test. If you don't have any better proposals, i can prepare another repo where i put files. Although there is a problem with optimisation under windows (freeDV you mention earlier).

I talked with Andreas this weekend and i get drawings of connectors on his pcb adapter for 3.2" lcd. I proposed that i can design such board to use witch 3.5 lcd from raspberry in SPI mode, also same display with removed that blue pcb below lcd (serial to parallel conversion) and added touch panel controller for use it in parallel mode. It will be matched to fit in mcHF and OVI40. I will start soon when i modify code to point where someone may test it. It takes long because concern of destroying something.
So far i modified the code to allow easy change location of items (ui_lcd_items.h), and change size of them. I'm still moving embedded positions to this file.
More about the lcd adapter: i will publish it that everyone may try to do it home (for people that does pcbs), but not commercial, and also  I will have some of them available to buy (not expensive).
And finally, YES! You have right about automated builds. I thinked about it but i don't have better way than you. It should be done in the way you started (i think the goal is use of simple and only one define if possible). At this level it seems that the only way is to add define to command line of compiler dependent of the hardware one may have.

73 Slawek

**Comment by sp9bsl** [comment]
Almost forgot, i will change the pin of CS (CSB) to CSA due to compatibility with OVI40 this afternoon, will it be a problem for you? Sorry for the mess.

**Comment by db4ple** [comment]
CSB to CSA -> not at all for me. Haven't yet started to wire the adapter anyway. 

I think it is important to keep differences as small as possible. Each variation without clear justification and benefit should be eliminated. Each variation should be implemented in a way that it causes as little as amount of maintenance and care.  Same pin on all platforms possible: we use the same pin. Same pin not possible: we need a way to "hide" this were it does not matter. E.g. in UHSDR firmware we use a label to refer to the pin in software and map this in uhsdr_board_config.h (not 100% true but we'll get there). 
Pro: Same name, Con: It is not clear which actual pin it is. But it is easy enough to find out and since we do not permanently reassign pins it works well enough.

**Comment by db4ple** [comment]
Automated Builds and storage: Shall I try to find a way to use travis to do this for us?

**Comment by sp9bsl** [comment]
Yes, it would be perfect! Please try Travis magic :)

**Comment by df8oe** [comment]
CSB to CSA -> that is important because CSB is not present on 34p LCD header of OVI40. I do want that LCD is plug&play hardware compatible to mcHF AND OVI40 - no rewiring neccessary.

**Comment by sp9bsl** [comment]
Andreas, it is present via the D11 pin (14 pin on OVI40) but it doesn't look good - my fault.
CS from LCD should be connected to CS pin on both boards.

**Comment by db4ple** [comment]
Hi,
I did some Travis Magic and finally have a working setup:
https://github.com/db4ple/mchf-github/releases
Check the end of the .travis.yml to see how I did this. 
Basically I said, for each tag run the deployment action. And finally simply let it collect a number of files.
This number should be limited or we pack everything in a zip, since the more files you have the more work is deleting a release.

Handling releases in github is kind of pain if you want to get rid of them:
https://help.github.com/articles/editing-and-deleting-releases/

Anyway, what I did was first  to install the travis commandline client on Windows. The I followed the instructions to setup the release mechanism and then fixed the content of the .travis.yml which was changed during autosetup of the release thing (but since it generates your API key, this is quite convenient). 

https://docs.travis-ci.com/user/deployment/releases/

BTW, some info on the .travis.yml on this page may be outdated (branch: vs. branches:). 

Slawek, I hope this gives you enough information to setup an automated build. We may need to add new build targets to build firmware for all 2 (or three) graphics drivers for easier testing. Header files are not yet ready for this, since we need to comment all USE_GFX_* defines out and only then we can set it via Makefile.

**Comment by sp9bsl** [comment]
Hi, 
good to hear that, i will check it in a while. Great job!

**Comment by sp9bsl** [comment]
Hi,
i will try at evening, but how can i trigger travis to build and generate files in my repo?

**Pull request merged**
